#!/bin/bash

set -e

cd /etc/swift

rm -f *.builder *.ring.gz backups/*.builder backups/*.ring.gz

swift-ring-builder object.builder create 10 3 1
swift-ring-builder object.builder add r1z1-127.0.0.1:6010/d1 1
swift-ring-builder object.builder add r1z2-127.0.0.2:6020/d2 1
swift-ring-builder object.builder add r1z3-127.0.0.3:6030/d3 1
swift-ring-builder object.builder add r1z4-127.0.0.4:6040/d4 1
swift-ring-builder object.builder rebalance
swift-ring-builder object-1.builder create 10 2 1
swift-ring-builder object-1.builder add r1z1-127.0.0.1:6010/d1 1
swift-ring-builder object-1.builder add r1z2-127.0.0.2:6020/d2 1
swift-ring-builder object-1.builder add r1z3-127.0.0.3:6030/d3 1
swift-ring-builder object-1.builder add r1z4-127.0.0.4:6040/d4 1
swift-ring-builder object-1.builder rebalance
swift-ring-builder object-2.builder create 10 6 1
swift-ring-builder object-2.builder add r1z1-127.0.0.1:6010/d1 1
swift-ring-builder object-2.builder add r1z1-127.0.0.1:6010/d5 1
swift-ring-builder object-2.builder add r1z2-127.0.0.2:6020/d2 1
swift-ring-builder object-2.builder add r1z2-127.0.0.2:6020/d6 1
swift-ring-builder object-2.builder add r1z3-127.0.0.3:6030/d3 1
swift-ring-builder object-2.builder add r1z3-127.0.0.3:6030/d7 1
swift-ring-builder object-2.builder add r1z4-127.0.0.4:6040/d4 1
swift-ring-builder object-2.builder add r1z4-127.0.0.4:6040/d8 1
swift-ring-builder object-2.builder rebalance
swift-ring-builder container.builder create 10 3 1
swift-ring-builder container.builder add r1z1-127.0.0.1:6011/d1 1
swift-ring-builder container.builder add r1z2-127.0.0.2:6021/d2 1
swift-ring-builder container.builder add r1z3-127.0.0.3:6031/d3 1
swift-ring-builder container.builder add r1z4-127.0.0.4:6041/d4 1
swift-ring-builder container.builder rebalance
swift-ring-builder account.builder create 10 3 1
swift-ring-builder account.builder add r1z1-127.0.0.1:6012/d1 1
swift-ring-builder account.builder add r1z2-127.0.0.2:6022/d2 1
swift-ring-builder account.builder add r1z3-127.0.0.3:6032/d3 1
swift-ring-builder account.builder add r1z4-127.0.0.4:6042/d4 1
swift-ring-builder account.builder rebalance
